# Generated by Django 5.2.7 on 2025-10-02 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 2, 18, 37, 50, 333200, tzinfo=datetime.timezone.utc)),
        ),
    ]
